signature = [
    34,
    94,
    125,
    19,
    113,
    129,
    1,
    254,
    222,
    37,
    77,
    59,
    21,
    235,
    106,
    193,
    166,
    124,
    104,
    4,
    118,
    162,
    234,
    211,
    115,
    66,
    94,
    150,
    59,
    199,
    57,
    183,
    59,
    250,
    14,
    152,
    118,
    130,
    19,
    3,
    212,
    55,
    92,
    127,
    128,
    188,
    84,
    190,
    85,
    212,
    225,
    151,
    89,
    155,
    47,
    162,
    87,
    134,
    208,
    226,
    7,
    161,
    5,
    168,
]
beta = "1498760273557913456370459222027449040163634869948415528344868600761947487523"
dlog_e = "2815834045141047248296014764766921370888833365641393041932225141550944894751"
dlog_s = "1023284613684976434280267589564951651741782634037934709388634324034792989992"
hashed_message = [
    218,
    239,
    222,
    213,
    190,
    193,
    112,
    62,
    182,
    226,
    19,
    202,
    51,
    169,
    222,
    157,
    155,
    222,
    83,
    32,
    18,
    31,
    187,
    249,
    49,
    128,
    244,
    131,
    204,
    206,
    107,
    226,
]
pub_key_x = [
    158,
    30,
    136,
    123,
    120,
    204,
    6,
    226,
    64,
    216,
    96,
    95,
    238,
    120,
    20,
    91,
    44,
    2,
    181,
    15,
    171,
    210,
    100,
    74,
    243,
    208,
    255,
    91,
    222,
    248,
    18,
    190,
]
pub_key_y = [
    151,
    145,
    124,
    206,
    255,
    36,
    241,
    99,
    254,
    200,
    250,
    151,
    236,
    57,
    81,
    36,
    165,
    7,
    139,
    205,
    215,
    77,
    194,
    49,
    9,
    177,
    21,
    157,
    90,
    29,
    26,
    7,
]

[oprf_pk]
x = "15003657924788399520423800501973962387080403835278072811641574091656004606719"
y = "14529415343323015636900366522580262473735574267701282924026299349812458958307"

[oprf_response]
x = "1065949620655181774308101197704033100236194646567058021926722685606992436847"
y = "14787959160106034745010522499467846959920195067540224472248153986015143882065"

[oprf_response_blinded]
x = "4412395052256565047298638251655830431466984686274840433808703772709569110803"
y = "20256127588343150090186757350315422452391433342385468273813865055940593724572"
