[package]
name = "prototype_oprf"
type = "bin"
authors = [""]

[dependencies]
poseidon2 = { tag = "v0.5.0-beta.0", git = "https://github.com/TaceoLabs/noir-poseidon", directory = "poseidon2" }
babyjubjub = { path = "../babyjubjub" }
oprf = { path = "../oprf" }
eddsa_poseidon2 = { path = "../eddsa_poseidon2" }
ecrecover = { path = "../ecrecover" }
